
/**
 * Footer component for professional invoice template
 */
import jsPDF from "jspdf";

/**
 * Render footer with professional design
 */
export const renderFooter = (
  doc: jsPDF, 
  colors: any, 
  pageWidth: number, 
  pageHeight: number
): void => {
  // Add footer background
  doc.setFillColor(250, 250, 250);
  doc.rect(0, pageHeight - 25, pageWidth, 25, 'F');
  
  // Add a thin line above footer
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(0, pageHeight - 25, pageWidth, pageHeight - 25);
  
  // Add thank you message
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(colors.text[0], colors.text[1], colors.text[2]);
  doc.text("Thank you for your business!", pageWidth / 2, pageHeight - 15, { align: "center" });
  
  // Add a powered by message
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by DigitBooks | www.digitbooks.com", pageWidth / 2, pageHeight - 8, { align: "center" });
};
