
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add Node.js version to ensure compatibility
[build.environment]
  NODE_VERSION = "18"
  CSV_ONLY_MODE = "true"

# Disable automatic deploys
[build.lifecycle]
  auto_deploy = false

# Add headers for CORS support
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
