
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Using dummy values to prevent actual database connection
const SUPABASE_URL = "https://example.com";
const SUPABASE_PUBLISHABLE_KEY = "dummy_key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Creating a mock client that will not actually connect to Supabase
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
